app/routes.py
"""
Program: Routes
Author: Maya Name
Creation Date: 12/30/2024
Revision Date: 02/03/2025
Description: Routes file for Flask microblog application

Revisions:
02/03/2025 Update text to support German translation

"""

import asyncio
import bleach
import sqlalchemy as sa
from datetime import datetime, timezone
from flask import Blueprint, current_app, flash, g, render_template, redirect, request, url_for
from flask_babel import _, get_locale
from flask_login import current_user, login_required, login_user, logout_user
from langdetect import detect, LangDetectException
from markupsafe import Markup
from sqlalchemy import desc
from urllib.parse import urlparse, urljoin
from app.config import Config
from app.forms import (LoginForm, SignupForm, EditProfileForm,
                       FollowForm, PostForm, ResetPasswordRequestForm,
                       ResetPasswordForm, SearchForm
                       )
from app.email import send_password_reset_email
from app.extensions import db
from app.models import User, Post
from app.trans import translate_text

pages = Blueprint('pages', __name__)

def is_safe_redirect_url(target):
    # Check if the url is safe for redirects 
    host_url = urlparse(request.host_url)
    redirect_url = urlparse(urljoin(request.host_url, target))
    return (
        redirect_url.scheme in ('http', 'https') and
        host_url.netloc == redirect_url.netloc
    )

@pages.before_request
def before_request():
    # Set date/time of last page view
    if current_user.is_authenticated:
        current_user.last_seen = datetime.now(timezone.utc)
        db.session.commit()
    # Set local formatting for date/time
    g.locale = str(get_locale())

# Application routes

@pages.route('/', methods=['GET', 'POST'])
@pages.route('/index/', methods=['GET', 'POST'])
def index():
    head_title = _('Home')
    page_title = _('Journal Posts')
    page = request.args.get('page', 1, type=int)

    # posts = db.session.scalars(db.select(Post).order_by(desc(Post.timestamp))).all()
    posts = db.paginate(db.select(Post).order_by(desc(Post.timestamp)),
                        page=page,
                        per_page = current_app.config['POSTS_PER_PAGE'],
                        # per_page=Config.POSTS_PER_PAGE,
                        error_out=False
                        )

    # Mark the sanitized HTML as safe
    for post in posts:
        post.body = Markup(post.body)


    return render_template('index.html',
                           head_title=head_title,
                           page_title=page_title,
                           posts=posts.items, 
                           pagination=posts,
                           )

@pages.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    head_title = _('Login')
    page_title = _('Journal Login')

    # Reroute to index if already logged in
    if current_user.is_authenticated:
        return redirect(url_for('pages.index'))

    if form.validate_on_submit():
        user = db.session.scalar(
            sa.select(User).where(User.username == form.username.data))
        if user is None or not user.check_password(form.password.data):
            flash(_('Invalid login. Check your username and password.'), 
                    'error')
            return redirect(url_for('pages.login'))
        login_user(user, remember=form.remember_me.data)
        # flash(f'{form.username.data} successfully logged in', 'success')
        flash(_('%(username)s successfully logged in' , username=form.username.data), 'success')

        # Check the 'next' parameter for safe redirection
        next_page = request.form.get('next') or request.args.get('next') 

        if next_page and is_safe_redirect_url(next_page):
            # Redirect safely
            return redirect(next_page)
        # Fallback to a default page
        return redirect(url_for('pages.index'))


    return render_template('login.html', 
                               head_title=head_title,
                               page_title=page_title, 
                               form=form)

@pages.route('/logout/', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    flash(_('Logged out successfully!'), 'success')

    next_page = request.form.get('next') or request.args.get('next') 
    if next_page and is_safe_redirect_url(next_page):
        return redirect(next_page)
    return redirect(url_for('pages.index'))

@pages.route('/signup/', methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    head_title = _('Sign Up')
    page_title = _('Journal Sign Up')

    # Reroute to index if already logged in
    if current_user.is_authenticated:
        return redirect(url_for('pages.index'))

    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        
        user.set_password(form.password.data)

        db.session.add(user)
        db.session.commit()
        # flash(f'{form.username.data} successfully signed up' , 'success')
        flash(_('%(username)s successfully signed up' , username=form.username.data), 'success')

        # Check the 'next' parameter for safe redirection
        next_page = request.form.get('next') or request.args.get('next') 

        if next_page and is_safe_redirect_url(next_page):
            # Redirect safely
            return redirect(next_page)
        # Fallback to a default page
        return redirect(url_for('pages.login'))
    

    return render_template('signup.html', 
                               head_title=head_title,
                               page_title=page_title, 
                               form=form)

@pages.route('/user/<username>')
@login_required
def user(username):
    head_title = _('User Profile')
    page = request.args.get('page', 1, type=int)

    user = db.first_or_404(sa.select(User).where(User.username == username))

    posts = db.paginate(current_user.following_posts().order_by(Post.timestamp.desc()),
                        page=page,
                        per_page=Config.POSTS_PER_PAGE,
                        error_out=False
                        )

    # Mark the sanitized HTML as safe
    for post in posts:
        post.body = Markup(post.body)

    # Set for follower/following form buttons
    form = FollowForm()

    return render_template('user.html', 
                           head_title=head_title,
                           user=user, 
                           posts=posts.items, 
                           pagination=posts,
                           form=form)

@pages.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    head_title = _('Edit Profile')
    page_title = _('Edit Profile')
    form = EditProfileForm()

    # Handles valid submit
    if form.validate_on_submit():
        current_user.firstname = form.firstname.data
        current_user.lastname = form.lastname.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Your changes have been saved.', 'success')
    
        # Check the 'next' parameter for safe redirection
        next_page = request.form.get('next') or request.args.get('next') 

        if next_page and is_safe_redirect_url(next_page):
            # Redirect safely
            return redirect(next_page)
        # Fallback to a default page
        return redirect(url_for('pages.edit_profile'))

    # Handles initial form display w/ current data
    elif request.method == 'GET':
        # Populate form with current data from database
        form.firstname.data = current_user.firstname
        form.lastname.data = current_user.lastname
        form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', 
                           head_title=head_title,
                           page_title=page_title,
                           form=form)

@pages.route('/follow/<username>', methods=['POST'])
@login_required
def follow(username):
    form = FollowForm()
    if form.validate_on_submit():
        user = db.session.scalar(
            sa.select(User).where(User.username == username))
        if user is None:
            flash(f'User {username} not found.', 
                    'error')
            return redirect(url_for('pages.index'))
        if user == current_user:
            flash('You cannot follow yourself!', 
                    'error')
            return redirect(url_for('pages.user', username=username))
        current_user.follow(user)
        db.session.commit()
        flash(f'You are following {username}!', 
                    'success')
        return redirect(url_for('pages.user', username=username))
    else:
        return redirect(url_for('pages.index'))

@pages.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    form = FollowForm()
    if form.validate_on_submit():
        user = db.session.scalar(
            sa.select(User).where(User.username == username))
        if user is None:
            flash(f'User {username} not found.', 
                    'error')
            return redirect(url_for('pages.index'))
        if user == current_user:
            flash('You cannot unfollow yourself!', 
                    'error')
            return redirect(url_for('pages.user', username=username))
        current_user.unfollow(user)
        db.session.commit()
        flash(f'You are not following {username}.', 
                    'success')
        return redirect(url_for('pages.user', username=username))
    else:
        return redirect(url_for('pages.index'))
    
@pages.route('/add_entry/', methods=['GET', 'POST'])
@login_required
def add_entry():
    head_title = _('Add Entry')
    page_title = _('Add Journal Entry')

    # Allowed elements for sanitized the entry input
    ALLOWED_TAGS = current_app.config['ALLOWED_TAGS']
    ALLOWED_ATTRIBUTES = current_app.config['ALLOWED_ATTRIBUTES']
    

app/templates/_header.html
<header class="header-nav">
    <p class="logo">Flask Journal</p>

    <!-- Add a conditional to check if form is defined --> 
    {% if search_form %} 
      <form class="header_search" method="post" action="{{ url_for('pages.search') }}" autocomplete="off"> 
          {{ search_form.hidden_tag() }} 
        <input class="search_form-input" type="search" name="searched" placeholder="Content in Title" aria-label="Search"> 
        <button class="search_btn" type="submit">
          Search
        </button> 
      </form> 
    {% else %}
      <p>Form not found.</p>
    {% endif %}
  

    <nav>
      <ul class="nav_links">
        <li><a class="nav_link" href="{{ url_for('pages.index') }}">{{_('Home')}}</a></li>
        {% if current_user.is_authenticated %}
          <li><a class="nav_link" href="{{ url_for('pages.user', username=current_user.username) }}">{{_('Profile')}}</a></li>
          <li><a class="nav_link" href="{{ url_for('pages.logout') }}">{{_('Logout')}}</a></li>
        {% else %}
          <li><a class="nav_link" href="{{ url_for('pages.login') }}">{{_('Login')}}</a></li>
        {% endif %}
        <li><a class="nav_link" href="{{ url_for('pages.about') }}">{{_('About')}}</a></li> 
      </ul>
    </nav>
    
</header>

app/templates/_post.html
<div class="post_container">
  <div class="post_heading">
    <span><img src="{{ post.author.avatar(36) }}"></span>
    <span class="post_title">{{ post.title}}</span>
  </div>
  <div id="post{{ post.id }}">
    <p>{{ post.body }}</p>
    By: <span class="post_author">{{ post.author.username }}</span> 
    <span class="post_posted">on: {{ moment(post.timestamp).format('LLL') }}</span> 
    <p>
      {% if post.language and post.language != g.locale %}
      <a class="text_link" href="{{ url_for('pages.trans_text', post_id=post.id) }}">Translate Entry</a>
      {% endif %}
      <a href="#" class="profile-link text_link" data-username="{{ post.author.username }}">Author Profile</a>
    </p>
  </div>
</div>

app/templates/_profile.html
{% extends "base_main.html" %}

{% block head_content %} 
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/profile.css') }}">
{% endblock %}

{% block main_content %}
  <section class="profile_section">
      <img class="user_img" src="{{ user.avatar(128) }}">
      <div class="user_info">
        <p class="info_title">
          {% if user.firstname %}
            {{ user.firstname }}
          {% else %}
            {{ user.username }}
          {% endif %}
          {% if user.lastname %}
            {{ user.lastname }}
          {% endif %}
        </p>
        <ul>
          <li><span class="list_category">User ID:</span>  {{ user.username }}</li>
          <li>
            <span class="list_category">Last seen:</span> 
            {% if user.last_seen %} 
              {{ moment(user.last_seen).format('LLL') }}
            {% endif %} 
          </li>
          <li>{% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}</li>

          <li>{{ user.followers_count() }} Follower {{ user.following_count() }} Following</li>
        </ul>

      </div>
    </section>
  {% endblock %}

app/templates/_profile_content.html
<section class="profile_section">
    <img class="user_img" src="{{ user.avatar(128) }}">
    <div class="user_info">
      <p class="info_title">
        {% if user.firstname %}
          {{ user.firstname }}
        {% else %}
          {{ user.username }}
        {% endif %}
        {% if user.lastname %}
          {{ user.lastname }}
        {% endif %}
      </p>
      <ul>
        <li><span class="list_category">User ID:</span>  {{ user.username }}</li>
        <li>
          <span class="list_category">Last seen:</span> 
          {% if user.last_seen %} 
            {{ moment(user.last_seen).format('LLL') }}
          {% endif %} 
        </li>
        <li>{% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}</li>

        <li>{{ user.followers_count() }} Follower {{ user.following_count() }} Following</li>
      </ul>
    </div>
  </section>

app/templates/about.html
{% extends 'base_main.html'%}


{% block head_content %} 
 
{% endblock %}

{% block main_content %}

<h1>{{ page_title }}</h1>
  
<div class="section">

 <h2>Description</h2>

 <p>
    This is a stripped down version of a micro-blog/journal application loosely based on the 2024 version of 
    the Flask Mega Tutorial series by Miguel Grinberg and several other tutorials. You can view code for the
    complete version of the application on <a class="text_link" href="https://github.com/mayaname/flask_blog" target="_blank">GitHub</a>.
  </p>

  <p>
    I have modified the application structure to suit my preferences, but still avoid circular imports. 
    As I am still learning about Flask, I am using this app as a journal of sorts for short posts on 
    Flask topics I find useful. I will also try to address some of the issues I encountered when deploying 
    to PythonAnywhere. While these are mostly for my reference, it is my hope that others will also find 
    them along with the application code of some use.
  </p>

  <h2>Changes from Flask Mega Tutorial</h2>

  <p>Here is where I deviated from the FMT</p>

  <ul>
    <li>Defined extensions like SQLAlchemy, Flash-Login, and Flask-Migrate in extensions.py</li>
    <li>Used standard CSS rather than Bootstrap</li>
    <li>Added Script to dismiss flash notification after 30 seconds in main.js</li>
    <li>Added Script to show/hide login password in login.js</li>
    <li>Defined post column in Post class to support larger text content (more journal like)</li>
    <li>Used a somewhat different code for errors.py to support common error.html file</li>
    <li>Used modified code from SendGrid for logging and password reset emails</li>
    <li>Changed index route to not require login, shows all journal entries in descending order</li>
    <li>Changed User profile page shows both user and following entries in descending order</li>
    <li>Moved the Add Journal Entry link to the User profile page</li>
    <li>Use Bleach and Markupsafe modules to securely allow formatting of post body content</li>
    <li>Used Babel to translation to German rather than Spanish</li>
    <li>Used googletrans as no credit card is required, Display entire translated post on separate page</li>
    <li>Used SQLAlchemy for navbar search form that searches the entry titles</li>
    <li>Added author mini-profiles (no journal entries) that are not restricted by login requirement</li>
    <li>Updated the author (user) mini-profile to be a modal popup</li>
    <li>Added an About page</li>


  </ul>

  <h2>Abnormally Normal's History</h2>

  <P>
    Abnormally Normal started over fifteen years ago when I took an online web development course through 
    John Hopkins University. A capstone project was to create a website for a fictitious customer. 
    Abnormally Normal became the fictitious web design company for the project. From this humble beginning,
    the 'company' created numerous project sites through the years for courses from Rice University, MIT, University of Michigan, 
    and many others. It is also used for personal projects such as this one. 
  </P>
</div>

{% endblock %}

app/templates/base_main.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/wolftrack.ico') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/main.css') }}">

  <script defer src="{{ url_for('static', filename='scripts/main.js') }}"></script>

  {% block head_content %} {% endblock %}

  {% if head_title %}
   <title>Flask Journal - {{ head_title }}</title>
  {% else %}
    <title>Flask Journal</title>
  {% endif %}

</head>
<body>
  <!-- Header section -->
  {% include '_header.html' %}

  <div class="flash_container">
    {% for category, message in get_flashed_messages(with_categories=true) %}
      <div class="flash {{ category }}" id="flash-message">
        <div class="left-section">!</div>
        <div class="right-section">
          {{ message }}
          <div class="close-btn" onclick="this.parentElement.parentElement.style.display='none';">x</div>
        </div>
      </div>
    {% endfor %}
  </div>

  <!-- Content section -->
  <main class="main">
      {% block main_content %} {% endblock %}
  </main>

  <!-- Footer section -->
  {% include '_footer.html' %}

  <!-- Script to convert timestamps -->
  {{ moment.include_moment() }}
  {{ moment.lang(g.locale) }}
</body>
</html>

app/templates/error.html
{% extends 'base_error.html' %}

{% set error_img = ERROR_IMG %}

{% block error_message %} 
<h3>{{ ERROR_HEADING }}</h3>
<p>{{ ERROR_MESSAGE_1 }}</p> 
<p>{{ ERROR_MESSAGE_2 }}</p> 
<p>{{ ERROR_MESSAGE_3 }}</p> 

{% endblock %}

{% block error_image %} 
    <img src="{{ url_for('static', filename='images/errors/' ~ error_img) }}" alt="Something went amok!" class="center">
{% endblock %}

app/templates/index.html
{% extends 'base_main.html'%}


{% block head_content %} 
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/modal.css') }}">
  <script defer src="{{ url_for('static', filename='scripts/profile.js') }}"></script>
{% endblock %}

{% block main_content %}

  {% if current_user.is_authenticated %}
    <!-- TODO Remove in production -->
    <h2>{{_('Hello')}}, {{ current_user.username }}!</h2>
  {% else %}
    <h1>{{_('Welcome to my Flash Journal!')}}</h1>
  {% endif %}

  <h1>{{ page_title }}</h1>
  
  <div class="section">

    {% for post in posts %}
      {% include '_post.html' %}
    {% endfor %}
  </div>

  <div class="pagination">
    {% if pagination.has_prev %}
        <a href="{{ url_for('pages.index', page=pagination.prev_num) }}">
          {{_('Previous')}}
        </a>
    {% else %}
        <span>{{_('Previous')}}</span>
    {% endif %}

    <span>Page {{ pagination.page }} of {{ pagination.pages }}</span>

    {% if pagination.has_next %}
        <a href="{{ url_for('pages.index', page=pagination.next_num) }}">
          {{_('Next')}}
        </a>
    {% else %}
        <span>{{_('Next')}}</span>
    {% endif %}
  </div>

  <div id="profileModal" class="modal">
    <div class="modal-content">
      <span class="close">&times;</span>
      <div id="profileContent">
        <!-- Profile details will be loaded here -->
      </div>
    </div>
  </div>

{% endblock %}

app/templates/reset_password.html
{% extends 'base_main.html'%}
{% from 'macros/svg_icons.html' import show, hide %}


{% block head_content %} 
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/forms.css') }}">
{% endblock %}

{% block main_content %}

<h1>{{ page_title }}</h1>

<section class="section_form">
  <form  class="form" method="post" novalidate>
    {{ form.hidden_tag() }}
    <div class="form_group">
      {{ form.password.label(class="form_label") }}
      {{ form.password(size=64, class="form_input", autocomplete="off", autofocus=true,) }}
      {% for error in form.password.errors %}
        <span class="form_error">[{{ error }}]</span>
      {% endfor %}
    </div>

    <div class="form_group">
        {{ form.password2.label(class="form_label") }}
        {{ form.password2(size=64, class="form_input", autocomplete="off") }}
        {% for error in form.password2.errors %}
          <span class="form_error">[{{ error }}]</span>
        {% endfor %}
      </div>

    <div class="form_submit">
      {{ form.submit(class="form_submit-button") }} 
    </div>
  </form>
  
    
</section>


{% endblock %}

app/templates/reset_password_request.html
{% extends 'base_main.html'%}
{% from 'macros/svg_icons.html' import show, hide %}


{% block head_content %} 
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/forms.css') }}">
{% endblock %}

{% block main_content %}

<h1>{{ page_title }}</h1>

<section class="section_form">
  <form  class="form" method="post" novalidate>
    {{ form.hidden_tag() }}
    <div class="form_group">
      {{ form.email.label(class="form_label") }}
      {{ form.email(size=64, class="form_input", autocomplete="off", autofocus=true,) }}
      {% for error in form.email.errors %}
        <span class="form_error">[{{ error }}]</span>
      {% endfor %}
    </div>

    <div class="form_submit">
      {{ form.submit(class="form_submit-button") }} 
    </div>
  </form>
    
</section>


{% endblock %}

app/templates/search.html
{% extends 'base_main.html'%}

{% block head_content %} 
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/forms.css') }}">
{% endblock %}

{% block main_content %}

  <h1 class="page_title">{{ page_title }}</h1>

  <h3  class="page_title">You searched for: {{ searched }}</h3>

  <!-- Display entry listings -->
  {% if posts %} 
    
    <div class="section">
      {% for post in posts %}
        {% include '_post.html' %}
      {% endfor %}
    </div>

    <!-- Pagination links -->
    <div class="pagination">
      {% if pagination.has_prev %}
          <a href="{{ url_for('pages.search', page=pagination.prev_num) }}">Previous</a>
      {% else %}
          <span>Previous</span>
      {% endif %}

      <span>Page {{ pagination.page }} of {{ pagination.pages }}</span>

      {% if pagination.has_next %}
          <a href="{{ url_for('pages.search', page=pagination.next_num) }}">Next</a>
      {% else %}
          <span>Next</span>
      {% endif %}
    </div>

  {% else %}
    <p class="table__empty">No entries were found that matched your search criteria.</p>
  {% endif %}



{% endblock %}

app/templates/signup.html
{% extends 'base_main.html'%}
{% from 'macros/svg_icons.html' import show, hide %}


{% block head_content %} 
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/forms.css') }}">
  <script defer src="{{ url_for('static', filename='scripts/login.js') }}"></script>
{% endblock %}

{% block main_content %}

<h1>{{ page_title }}</h1>

<section class="section_form">
  <form  class="form" method="post" novalidate>
    {{ form.hidden_tag() }}

    <div class="form_group">
      {{ form.firstname.label(class="form_label") }}
      {{ form.firstname(size=32, class="form_input", autocomplete="off", autofocus=true,) }}
      {% for error in form.firstname.errors %}
        <span class="form_error">[{{ error }}]</span>
      {% endfor %}
    </div>

    <div class="form_group">
      {{ form.lastname.label(class="form_label") }}
      {{ form.lastname(size=32, class="form_input", autocomplete="off") }}
      {% for error in form.lastname.errors %}
        <span class="form_error">[{{ error }}]</span>
      {% endfor %}
    </div>

    <div class="form_group">
      {{ form.username.label(class="form_label") }}
      {{ form.username(size=32, class="form_input", autocomplete="off") }}
      {% for error in form.username.errors %}
        <span class="form_error">[{{ error }}]</span>
      {% endfor %}
    </div>

    <div class="form_group">
      {{ form.email.label(class="form_label") }}
      {{ form.email(size=32, class="form_input", autocomplete="off") }}
      {% for error in form.email.errors %}
        <span class="form_error">[{{ error }}]</span>
      {% endfor %}
    </div>

    <div class="form_group">
      {{ form.password.label(class="form_label" ) }}
      {{ form.password(class="size=32, form_input", autocomplete="off") }} 
      {% for error in form.password.errors %}
      <span class="form_error">[{{ error }}]</span>
      {% endfor %}
    </div>
  

    <div class="form_group">
      {{ form.password2.label(class="form_label" ) }}
      {{ form.password2(class="size=32, form_input",  autocomplete="off") }} 
      {% for error in form.password2.errors %}
      <span class="form_error">[{{ error }}]</span>
      {% endfor %}
    </div>
      
    <div class="form_submit">
      {{ form.submit(class="form_submit-button") }} 
    </div>

    <p>Already Registered? <a class="text_link" href="{{ url_for('pages.login') }}">Log In!</a></p>
  </form>
</section>


{% endblock %}

app/templates/trans_text.html
{% extends 'base_main.html'%}


{% block head_content %} 
  
{% endblock %}


{% block main_content %}

<h1>{{ page_title }}</h1>

<h3>Translation by Google Translate</h3>

<div class="section">

  <div class="post_container">
    <div class="post_heading">
      <span><img src="{{ post.author.avatar(36) }}"></span>
      <span class="post_title">{{ translated_title}}</span>
    </div>
    <p>{{ translated_body }}</p>
    By: <span class="post_author">{{ post.author.username }}</span> 
    <span class="post_posted">on: {{ moment(post.timestamp).format('LLL') }}</span> 
  </div>
</div>





{% endblock %}

app/templates/user.html
{% extends "base_main.html" %}

{% block head_content %} 
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/profile.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/forms.css') }}">
{% endblock %}

{% block main_content %}

  <!-- Footer section -->
  {% include '_profile.html' %}


  <div class="section">
    {% for post in posts %}
      {% include '_post.html' %}
    {% endfor %}
  </div>

  <div class="pagination">
    {% if pagination.has_prev %}
        <a href="{{ url_for('pages.user', username=user.username, page=pagination.prev_num) }}">
          Previous
        </a>
    {% else %}
        <span>Previous</span>
    {% endif %}

    <span>Page {{ pagination.page }} of {{ pagination.pages }}</span>

    {% if pagination.has_next %}
        <a href="{{ url_for('pages.user', username=user.username, page=pagination.next_num) }}">
          Next
        </a>
    {% else %}
        <span>Next</span>
    {% endif %}
  </div>

{% endblock %}